almacenieez/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('usuario/', include('usuario.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('tipoproducto/', include('productos.urls_tipoproducto')),
    path('solicitudes/', include('solicitudes.urls')),

]

departamentos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'departamentos'

urlpatterns = [
    path('lista/', login_required(views.DepartamentoList.as_view()), name='lista'),
    path('nuevo/', login_required(views.DepartamentoCrear.as_view()), name='nuevo'),
    path('eliminar/<int:pk>', views.DepartamentoDelete.as_view(), name='eliminar'),

]

productos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'productos'

urlpatterns = [
    path('lista/', login_required(views.ProductoList.as_view()), name='lista'),
    path('nuevo/', login_required(views.nuevo_producto), name='nuevo'),
    path('editar/<int:pk>', views.ProductoActualizar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.ProductoDelete.as_view(), name='eliminar'),
    


]

proveedores/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'proveedores'

urlpatterns = [
    path('lista/', login_required(views.ProveedorList.as_view()), name='lista'),
    path('nuevo/', login_required(views.ProveedorCrear.as_view()), name='nuevo'),
    path('ver/<int:pk>', views.ProveedorDetalle.as_view(), name='ver'),
    path('editar/<int:pk>', views.ProveedorActualizar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.ProveedorDelete.as_view(), name='eliminar'),
]

solicitudes/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'solicitudes'

urlpatterns = [
    path('lista/', login_required(views.SolicitudList.as_view()), name='lista'),
    path('nuevo/', login_required(views.solicitud_nueva), name='nuevo'),
    path('aceptar/<int:id>', views.aceptar_solicitud, name='aceptar'),
    
    
]

usuario/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'usuario'

urlpatterns = [    
    path('nuevo/', login_required(views.NuevoUsuario.as_view()), name='nuevo'),
    path('lista/', login_required(views.UsuariosList.as_view()), name='lista'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('logout/', login_required(views.logout_view), name='logout'),
    path('cambia_grupo/<int:id_gpo>/<int:id_usuario>', login_required(views.cambia_grupo), name='cambia_grupo'),
    
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Usuario(User):
    rfc = models.CharField(
        'RFC',
        max_length=20,
        null=True,
        blank=False)

usuario/forms.py
from django import forms
from .models import Usuario

class UsuarioForm(forms.ModelForm):
   
    class Meta:
        model = Usuario

        fields = ('first_name','username','password','rfc')
        widgets = {
            'password': forms.PasswordInput(attrs={'class':'forms-control', 'placeholder':'Contraseña'})
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

usuario/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from .models import Usuario
from .forms import UsuarioForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin


# Create your views here.
class NuevoUsuario(PermissionRequiredMixin, CreateView):
    permission_required = ['usuario.manager_permiso'] 
    model = Usuario
    form_class = UsuarioForm
    extra_context = {'etiqueta':'Nuevo', 'boton':'Agregar', 'nuevo_user':True}
    success_url = reverse_lazy('usuario:lista')

    def form_valid(self, form):
        user = form.save(commit=False)
        # user.is_active = 0
        # print (user)
        return super().form_valid(form)
    
class UsuariosList(PermissionRequiredMixin, ListView):
    permission_required = ['usuario.manager_permiso'] 
    model = Usuario
    context_object_name = 'usuarios'
    lista_grupos = Group.objects.all()
    extra_context={'user_lista':True,
                    'lista_grupos': lista_grupos}

class LoginUsuario(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm

#cerrar sesion
def logout_view(request):
    logout(request)
    return redirect('usuario:login')

@login_required
@permission_required('auth.administrador_permiso', raise_exception=True)
def obtiene_usuario_grupo(request, id):
    if request.method != 'GET':
        return JsonResponse({'error':_('peticion incorrecta')},safe=False, status=403)
    id_usuario = request.GET.get('id')
    grupos = Groups.objects.filter(user_id=id_usuario)
    json=[]
    if not grupos:
        json.append({'error': _('sin grupos asignados')})
    for group in grupos:
        json.append({'id usuario':id_usuario,
        'id_grupo':grupo})
    return JsonResponse(json, safe=False)


def cambia_grupo(request, id_gpo, id_usuario):
    grupo = Group.objects.get(id=id_gpo)
    usuario= Usuario.objects.get(id=id_usuario)

    if grupo in usuario.groups.all():
        if usuario.groups.count() <= 1:
            messages.error(request, 'El usuario debe pertenecer a un grupo minimo')
        else:
            usuario.groups.remove(grupo)
            messages.success(request, 'El usuario ya no pertenece al grupo')
    else:
        usuario.groups.add(grupo)
        messages.success(request, 'El usuario se agrego al grupo')

    return redirect('usuario:lista')

usuario/templates/base3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="img/icons/icon-48x48.png" />

	<link rel="canonical" href="https://demo-basic.adminkit.io/pages-blank.html" />
	

	{% block css %}

    {% endblock css %}

	
	<title>
        {% block titulo %}

        {% endblock titulo %}
    </title>
	
	<link href="css/app.css" rel="stylesheet">
	<link href="{% static 'css/app.css' %}" rel="stylesheet">
</head>

<body>
	<div class="wrapper" >
		<nav id="sidebar" class="sidebar js-sidebar">
			<div class="sidebar-content js-simplebar">
				<a class="sidebar-brand" href="index.html">
          			<span class="align-middle">IEEZ</span>
        		</a>

				<ul class="sidebar-nav">
					<li class="sidebar-header">
						Pages
					</li>



					
              									<li class="sidebar-item">
						<a class="sidebar-link"  href="{% url 'solicitudes:lista' %}">
              				<i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Solicitudes</span>
              				
            			</a>
					</li>
            			</a>
					</li>

					{% if perms.auth.administrador_permiso or perms.usuario.manager_permiso %}
					<li class="sidebar-item">
						<a class="sidebar-link"  href="{% url 'productos:lista' %}">
              				<i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Productos</span>
            			</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'tipoproducto:lista' %}">
              				<i class="align-middle" data-feather="user"></i> <span class="align-middle">Materiales</span>
           				</a>
					</li>
					
					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'usuario:lista' %}">
              				<i class="align-middle" data-feather="log-in"></i> <span class="align-middle">Usuarios</span>
            			</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'proveedores:lista' %}">
              				<i class="align-middle" data-feather="user-plus"></i> <span class="align-middle">Proveedores</span>
            			</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'departamentos:lista' %}">
              				<i class="align-middle" data-feather="book"></i> <span class="align-middle">Departamentos</span>
            			</a>
					
				</ul>
				{% endif %}


				<div class="sidebar-cta">
					
				</div>
			</div>
		</nav>

		<div class="main">
			<nav class="navbar navbar-expand navbar-light navbar-bg">
				<a class="sidebar-toggle js-sidebar-toggle">
          <i class="hamburger align-self-center"></i>
        </a>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav navbar-align">
						
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
                <i class="align-middle" data-feather="settings"></i>
              </a>

							<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                				<span class="text-dark">Opciones</span>
              				</a>
							<div class="dropdown-menu dropdown-menu-end">
								
								<a class="dropdown-item" href="{% url 'usuario:logout' %}">Cerrar Sesión</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>

			<main class="content">
				<div class="container-fluid p-0">

					

					<div class="row">
						<div class="col-12">
							<div class="card">
								
								<div class="card-body">
									{% block contenido %}

    								{% endblock contenido %}
								</div>
							</div>
						</div>
					</div>

				</div>
			</main>

			<footer class="footer">
				<div class="container-fluid">
				
				</div>
			</footer>
		</div>
	</div>

	<script src="js/app.js"></script>
	<script src="https://unpkg.com/@adminkit/core@latest/dist/js/app.js%22%3E"></script>

	{% block js %}
	<script src="{% static 'js/app.js' %}"></script>
	<script src="{% static 'js/app.js.map' %}"></script>
    {% endblock js %}

</body>

</html>

usuario/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Login</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"> 

    <!-- FontAwesome JS-->
    <script defer src="{% static 'js/all.min.js' %}"></script>

    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/portal.css' %}">

</head> 

<body class="app app-login p-0">    

	{% if form.errors %}
		<div class="alert alert-warning">
			<p>Usuario no encontrado</p>
		</div>
	{% endif %}
	
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{% if message.tags == 'error'%}danger{%else%}success{%endif%}">
				{{message}}
			</div>
		{% endfor %}
			
	{% endif %}
		

    <div class="row g-0 app-auth-wrapper">
	    <div class="col-500 col-md-280 col-lg-300 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="index.html"><img class="logo-icon mr-2" src="{% static 'img/photos/ieez-logo.svg' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Inicia sesion</h2>
			        <div class="auth-form-container text-left">
						<form class="auth-form login-form" method="POST">
							{% csrf_token %}       
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">Usuario</label>
								<input id="id_username" name="username"  type="text" class="form-control signin-email" placeholder="Usuario" required="required" >
							</div><!--//form-group-->
							<div class="password mb-3">
								<label class="sr-only" for="signin-password">Contraseña</label>
								<input id="id_password" name="password" type="password" class="form-control signin-password" placeholder="Contraseña" required="required" >
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										
									</div><!--//col-6-->
									<div class="col-6">
										
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" id="btn_ingresar" style="background-color:#282c3c" class="btn app-btn-primary btn-block theme-btn mx-auto">Ingresar</button>
							</div>
							<input type="hidden" name="next" value="{{next}}">
						</form>

					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->

			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>

				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    

    </div><!--//row-->


</body>
</html> 