almacenieez/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('usuario/', include('usuario.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('tipoproducto/', include('productos.urls_tipoproducto')),
    path('solicitudes/', include('solicitudes.urls')),

]

productos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'productos'

urlpatterns = [
    path('lista/', login_required(views.ProductoList.as_view()), name='lista'),
    path('nuevo/', login_required(views.nuevo_producto), name='nuevo'),
    path('editar/<int:pk>', views.ProductoActualizar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.ProductoDelete.as_view(), name='eliminar'),
    


]

usuario/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'usuario'

urlpatterns = [    
    path('nuevo/', login_required(views.NuevoUsuario.as_view()), name='nuevo'),
    path('lista/', login_required(views.UsuariosList.as_view()), name='lista'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('logout/', login_required(views.logout_view), name='logout'),
    path('cambia_grupo/<int:id_gpo>/<int:id_usuario>', login_required(views.cambia_grupo), name='cambia_grupo'),
    
]

productos/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Producto(models.Model):
    #nombre = models.CharField("Nombre", max_length=30, unique=False)
    nombre = models.ForeignKey(
        "productos.TipoProducto",
        verbose_name="Nombre",
        null=True,
        blank=False,
        on_delete=models.SET_NULL)
    precio = models.DecimalField(
        'Precio',
        blank=False,
        max_digits=6,
        decimal_places=2,
        validators=[
            MinValueValidator(0)])
    cantidad = models.PositiveIntegerField('Cantidad', default=1)
    
    fecha = models.DateTimeField(auto_now_add=True)
    proveedor=models.ForeignKey(
        "proveedores.Proveedor",
        verbose_name="Proveedor",
        null=True,
        blank=False,
        on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.nombre)

    #def get_precio_total(self):
    #s    return cantidad * precio


class TipoProducto(models.Model):
    nombre = models.CharField(max_length=50, blank=False)
    cantidad = models.IntegerField('Cantidad', default=0, blank=False)


    def __str__(self):
        return self.nombre

productos/forms.py
from django import forms
from .models import Producto, TipoProducto

class TipoProductoForm(forms.ModelForm):
    class Meta:
        model = TipoProducto
        fields  = ('nombre',)

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        widgets = {
            # 'nombre':forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Nombre del Material', 'onFOcus':'validar{this}'}),
            'nombre': forms.Select(attrs={'class': 'form-control'}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'}),
            'fecha': forms.DateField(),
            'proveedor':forms.Select(attrs={'class': 'form-control'}),

        }

productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Producto, TipoProducto
from .forms import ProductoForm, TipoProductoForm
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.
@login_required
@permission_required('usuario.manager_permiso', raise_exception=True)
def lista_tipoproducto(request):
    tipoproductos = TipoProducto.objects.all()
    context = {'tipoproductos': tipoproductos, "cat_lista":True}
    return render(request, 'tipoproducto_list.html', context)

@login_required
@permission_required('usuario.manager_permiso', raise_exception=True)
def nuevo_tipoproducto(request):
    form = TipoProductoForm()
    if request.method == 'POST':
        form = TipoProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tipoproducto:lista')

    context = {'form' : form, "tmt_nueva":True}
    return render(request, 'tipoproducto_form.html', context)

def eliminar_tipoproducto(request, id):
    tipoproducto = get_object_or_404(TipoProducto, id=id)
    tipoproducto.delete()
    
    return redirect('tipoproducto:lista')

@login_required
@permission_required('usuario.manager_permiso', raise_exception=True)
def editar_tipoproducto(request, id):
    tipoproducto = get_object_or_404(TipoProducto, id=id)
    form = TipoProductoForm(instance=tipoproducto)
    if request.method == 'POST':
        form = TipoProductoForm(request.POST, instance=tipoproducto)
        if form.is_valid():
            form.save()
            return redirect('tipoproducto:lista')
    context = {'form' : form, "cat_edit":True}
    return render(request, 'editar_tipoproducto.html', context)  

class ProductoList(PermissionRequiredMixin, ListView):
    permission_required = ['usuario.manager_permiso']
    paginate_by = 10
    model = Producto
    context_object_name = 'productos'
    extra_context = {'etiqueta': 'Lista', 'mt_lista': True}

class ProductoCrear(PermissionRequiredMixin, CreateView):
    model = Producto
    form_class = ProductoForm
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar', 'mt_nuevo': True}
    success_url = reverse_lazy('productos:lista')

@login_required
@permission_required('usuario.manager_permiso', raise_exception=True)
def nuevo_producto(request):
    form = ProductoForm()
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            tipoproducto = TipoProducto.objects.get(id = request.POST['nombre'])
            cantidad= form.cleaned_data.get("cantidad")
            tipoproducto.cantidad += cantidad
            form.save()
            tipoproducto.save()
            return redirect('productos:lista')

    context = {'form' : form}
    return render(request, 'productos/producto_form.html', context)


class ProductoActualizar(PermissionRequiredMixin, UpdateView):
    permission_required = ['usuario.manager_permiso']
    model = Producto
    form_class = ProductoForm
    extra_context = {
        'etiqueta': 'Actualizar',
        'boton': 'Guardar',
        'mt_edit': True}
    success_url = reverse_lazy('productos:lista')

class ProductoDelete(DeleteView):
    model = Producto
    extra_context = {'etiqueta': 'Eliminar', 'mt_del': True}
    success_url = reverse_lazy('productos:lista')

productos/templates/productos/producto_confirm_delete.html
{% extends 'base3.html' %}
{% block contenido %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Producto</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Quieres eliminar el producto "{{ object }}"?</p>
        <input type="submit" value="Sí, si quiero">
        <a href="{% url 'productos:lista' %}">Mejor no</a>
    </form>
</body>
</html>
{% endblock contenido %}

productos/templates/productos/producto_form.html
{% extends 'base3.html' %}

{% block titulo %}
    {{etiqueta}} Producto
{% endblock titulo %}


{% block contenido %}

    <h1 class="app-page-title">{{etiqueta}} Producto</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-info">{{boton}} Aceptar</button>
    </form>


{% endblock contenido %}

productos/templates/productos/producto_list.html
{% extends 'base3.html' %}


{% block titulo %}
    Lista de productos
{% endblock titulo %}


{% block contenido %}


<h1 class="h3 mb-3">Lista de productos adquiridos</h1>


<hr>
<a href="{% url 'productos:nuevo' %}" class="btn btn-primary" style="background-color:#0a0a0a">Nuevo Producto</a>
<a href="{% url 'tipoproducto:lista' %}" class="btn btn-primary" style="background-color:#0a0a0a">Materiales</a>



<br>
<br>
<table class="table">
    <thead class="table-dark">
        <th>Nombre</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th>Fecha</th>
        <th>Proveedor</th>
        <th>Acciones</th>
        
    </thead>
    <tbody>
        {% for producto in productos  %}
        <tr>
            <td>{{producto.nombre}}</td>
            <td>{{producto.precio}}</td>
            <td>{{producto.cantidad}}</td>
            <td>{{producto.fecha}}</td>
            <td>{{producto.proveedor}}</td>
            
            <td>   
                <div lass="btn-group" role="group" aria-label="Basic outlined example">
                    <a  method="POST" href="{% url 'productos:eliminar' producto.id %}"  class="btn btn-primary">Eliminar</a>
                    <a  method="POST" href="{% url 'productos:editar' producto.id %}"  class="btn btn-primary">Editar</a>
                </div>
            </td>

            
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock contenido %}