almacenieez/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('usuario/', include('usuario.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('tipoproducto/', include('productos.urls_tipoproducto')),
    path('solicitudes/', include('solicitudes.urls')),

]

proveedores/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'proveedores'

urlpatterns = [
    path('lista/', login_required(views.ProveedorList.as_view()), name='lista'),
    path('nuevo/', login_required(views.ProveedorCrear.as_view()), name='nuevo'),
    path('ver/<int:pk>', views.ProveedorDetalle.as_view(), name='ver'),
    path('editar/<int:pk>', views.ProveedorActualizar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.ProveedorDelete.as_view(), name='eliminar'),
]

usuario/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'usuario'

urlpatterns = [    
    path('nuevo/', login_required(views.NuevoUsuario.as_view()), name='nuevo'),
    path('lista/', login_required(views.UsuariosList.as_view()), name='lista'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('logout/', login_required(views.logout_view), name='logout'),
    path('cambia_grupo/<int:id_gpo>/<int:id_usuario>', login_required(views.cambia_grupo), name='cambia_grupo'),
    
]

proveedores/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Proveedor(models.Model):
    nombre = models.CharField("Nombre", max_length=50, blank=False, unique=False)
    razonsocial = models.CharField(
        'Razón Social',
        max_length=60,
        null=True,
        blank=False)
    domicilio = models.CharField(
        'Domicilio',
        max_length=60,
        null=True,
        blank=False)
    telefono = models.BigIntegerField("Teléfono")
    rfc = models.CharField(
        'RFC',
        max_length=13,
        null=True,
        blank=False)
    correoelectronico = models.CharField("E-mail",max_length=50, default='', blank=False, null=True)
    regimenfiscal = models.CharField(
        'Regimen Fiscal',
        max_length=70,
        null=True,
        blank=False)
    
    #nombre = models.ForeignKey("materiales.TipoMaterial", verbose_name="Nombre", on_delete=models.CASCADE) 

    def __str__ (self):
        return self.nombre

    

proveedores/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = '__all__'
        widgets = {
            # 'nombre':forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Nombre del Material', 'onFOcus':'validar{this}'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'razonsocial': forms.TextInput(attrs={'class': 'form-control'}),
            'domicilio': forms.TextInput(attrs={'class': 'form-control'}),
            #'domicilio': forms.Textarea(attrs={'rows':2, 'cols':20,'class': 'form-control'}),
            'telefono': forms.NumberInput(attrs={'class': 'form-control'}),
            'rfc': forms.TextInput(attrs={'class': 'form-control'}),
            'correoelectronico': forms.TextInput(attrs={'class': 'form-control'}),
            'regimenfiscal': forms.TextInput(attrs={'class': 'form-control'}),




        }

proveedores/views.py
from django.shortcuts import render, redirect
from .models import Proveedor
from .forms import ProveedorForm
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.
class ProveedorList(PermissionRequiredMixin, ListView):
    permission_required = ['usuario.manager_permiso']
    paginate_by = 10
    model = Proveedor
    context_object_name = 'proveedores'
    extra_context = {'etiqueta': 'Lista', 'mt_lista': True}

class ProveedorCrear(PermissionRequiredMixin, CreateView):
    permission_required = ['usuario.manager_permiso']
    model = Proveedor
    form_class = ProveedorForm
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar', 'mt_nuevo': True}
    success_url = reverse_lazy('proveedores:lista')

class ProveedorDetalle(PermissionRequiredMixin, DetailView):
    permission_required = ['usuario.manager_permiso']
    model = Proveedor

class ProveedorActualizar(PermissionRequiredMixin, UpdateView):
    permission_required = ['usuario.manager_permiso']
    model = Proveedor
    form_class = ProveedorForm
    extra_context = {
        'etiqueta': 'Actualizar',
        'boton': 'Guardar',
        'mt_edit': True}
    success_url = reverse_lazy('proveedores:lista')

class ProveedorDelete(DeleteView):
    model = Proveedor
    extra_context = {'etiqueta': 'Eliminar', 'mt_del': True}
    success_url = reverse_lazy('proveedores:lista')

proveedores/templates/proveedores/proveedor_confirm_delete.html
{% extends 'base3.html' %}
{% block contenido %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Departamento</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Quieres eliminar el proveedor "{{ object }}"?</p>
        <input type="submit" value="Sí, si quiero">
        <a href="{% url 'proveedores:lista' %}">Mejor no</a>
    </form>
</body>
</html>
{% endblock contenido %}

proveedores/templates/proveedores/proveedor_detail.html
{% extends 'base3.html' %}


{% block titulo %}
    Detalle de proveedor
{% endblock titulo %}


{% block contenido %}


<br>
<div class="card" style="width: 18rem;">
    <div class="card-header">
        <b>{{object.nombre}}</b>
    </div>
    <div class="card-body">
        <!--<h5 class="card-title" class="card-header">{{object.titulo}}</h1>-->
        <p class="card-text">Razón Social: {{object.razonsocial}}</p>
        <p class="card-text">Domicilio: {{object.domicilio}}</p>
        <p class="card-text">Teléfono: {{object.telefono}}</p>
        <p class="card-text">RFC: {{object.rfc}}</p>
        <p class="card-text">Correo electrónico: {{object.correoelectronico}}</p>
        <p class="card-text">Régimen Fiscal: {{object.regimenfiscal}}</p>

        {% if object.descripcion %}
            <div class="card-subtitle mb-2 text-muted">
                {{object.descripcion}}
            </div>
        {% endif %}

        
    </div>
    
</div>
<br>
<a href="{% url 'proveedores:lista' %}" class="btn btn-primary">Regresar</a>

{% endblock contenido %}

proveedores/templates/proveedores/proveedor_form.html
{% extends 'base3.html' %}

{% block titulo %}
    {{etiqueta}} Proveedor
{% endblock titulo %}


{% block contenido %}

    <h1 class="app-page-title">{{etiqueta}} Proveedor</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-info">{{boton}}</button>
    </form>


{% endblock contenido %}

proveedores/templates/proveedores/proveedor_list.html
{% extends 'base3.html' %}


{% block titulo %}
    Lista de proveedores
{% endblock titulo %}


{% block contenido %}


<h1>Lista de proveedores registrados</h1>

<hr>
<a href="{% url 'proveedores:nuevo' %}" class="btn btn-primary" style="background-color:#0a0a0a">Nuevo Proveedor</a>
<br>
<br>
<table class="table">
    <thead class="table-dark">
        <th>Nombre</th>
        <th>Razón Social</th>
        <th>Dirección</th>
        <th>Teléfono</th>
        <th>Acciones</th>
        
    </thead>
    <tbody>
        {% for proveedor in proveedores  %}
        <tr>
            <td>{{proveedor.nombre}}</td>
            <td>{{proveedor.razonsocial}}</td>
            <td>{{proveedor.domicilio}}</td>
            <td>{{proveedor.telefono}}</td>
            <td>
                <div lass="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'proveedores:ver' proveedor.id %}" class="btn btn-outline-primary">Detalles</a>
                    <a class="btn btn-outline-primary" href="{% url 'proveedores:editar' proveedor.id %}">Editar<a>
                    <a class="btn btn-outline-primary" href="{% url 'proveedores:eliminar' proveedor.id %}">Eliminar<a>
                </div>
            </td>

            <td></td>
            <td></td>

            
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock contenido %}