almacenieez/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('usuario/', include('usuario.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('tipoproducto/', include('productos.urls_tipoproducto')),
    path('solicitudes/', include('solicitudes.urls')),

]

departamentos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'departamentos'

urlpatterns = [
    path('lista/', login_required(views.DepartamentoList.as_view()), name='lista'),
    path('nuevo/', login_required(views.DepartamentoCrear.as_view()), name='nuevo'),
    path('eliminar/<int:pk>', views.DepartamentoDelete.as_view(), name='eliminar'),

]

productos/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'productos'

urlpatterns = [
    path('lista/', login_required(views.ProductoList.as_view()), name='lista'),
    path('nuevo/', login_required(views.nuevo_producto), name='nuevo'),
    path('editar/<int:pk>', views.ProductoActualizar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.ProductoDelete.as_view(), name='eliminar'),
    


]

proveedores/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'proveedores'

urlpatterns = [
    path('lista/', login_required(views.ProveedorList.as_view()), name='lista'),
    path('nuevo/', login_required(views.ProveedorCrear.as_view()), name='nuevo'),
    path('ver/<int:pk>', views.ProveedorDetalle.as_view(), name='ver'),
    path('editar/<int:pk>', views.ProveedorActualizar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.ProveedorDelete.as_view(), name='eliminar'),
]

usuario/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'usuario'

urlpatterns = [    
    path('nuevo/', login_required(views.NuevoUsuario.as_view()), name='nuevo'),
    path('lista/', login_required(views.UsuariosList.as_view()), name='lista'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('logout/', login_required(views.logout_view), name='logout'),
    path('cambia_grupo/<int:id_gpo>/<int:id_usuario>', login_required(views.cambia_grupo), name='cambia_grupo'),
    
]

proveedores/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Proveedor(models.Model):
    nombre = models.CharField("Nombre", max_length=50, blank=False, unique=False)
    razonsocial = models.CharField(
        'Razón Social',
        max_length=60,
        null=True,
        blank=False)
    domicilio = models.CharField(
        'Domicilio',
        max_length=60,
        null=True,
        blank=False)
    telefono = models.BigIntegerField("Teléfono")
    rfc = models.CharField(
        'RFC',
        max_length=13,
        null=True,
        blank=False)
    correoelectronico = models.CharField("E-mail",max_length=50, default='', blank=False, null=True)
    regimenfiscal = models.CharField(
        'Regimen Fiscal',
        max_length=70,
        null=True,
        blank=False)
    
    #nombre = models.ForeignKey("materiales.TipoMaterial", verbose_name="Nombre", on_delete=models.CASCADE) 

    def __str__ (self):
        return self.nombre

    

proveedores/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = '__all__'
        widgets = {
            # 'nombre':forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Nombre del Material', 'onFOcus':'validar{this}'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'razonsocial': forms.TextInput(attrs={'class': 'form-control'}),
            'domicilio': forms.TextInput(attrs={'class': 'form-control'}),
            #'domicilio': forms.Textarea(attrs={'rows':2, 'cols':20,'class': 'form-control'}),
            'telefono': forms.NumberInput(attrs={'class': 'form-control'}),
            'rfc': forms.TextInput(attrs={'class': 'form-control'}),
            'correoelectronico': forms.TextInput(attrs={'class': 'form-control'}),
            'regimenfiscal': forms.TextInput(attrs={'class': 'form-control'}),




        }

proveedores/views.py
from django.shortcuts import render, redirect
from .models import Proveedor
from .forms import ProveedorForm
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.
class ProveedorList(PermissionRequiredMixin, ListView):
    permission_required = ['usuario.manager_permiso']
    paginate_by = 10
    model = Proveedor
    context_object_name = 'proveedores'
    extra_context = {'etiqueta': 'Lista', 'mt_lista': True}

class ProveedorCrear(PermissionRequiredMixin, CreateView):
    permission_required = ['usuario.manager_permiso']
    model = Proveedor
    form_class = ProveedorForm
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar', 'mt_nuevo': True}
    success_url = reverse_lazy('proveedores:lista')

class ProveedorDetalle(PermissionRequiredMixin, DetailView):
    permission_required = ['usuario.manager_permiso']
    model = Proveedor

class ProveedorActualizar(PermissionRequiredMixin, UpdateView):
    permission_required = ['usuario.manager_permiso']
    model = Proveedor
    form_class = ProveedorForm
    extra_context = {
        'etiqueta': 'Actualizar',
        'boton': 'Guardar',
        'mt_edit': True}
    success_url = reverse_lazy('proveedores:lista')

class ProveedorDelete(DeleteView):
    model = Proveedor
    extra_context = {'etiqueta': 'Eliminar', 'mt_del': True}
    success_url = reverse_lazy('proveedores:lista')

proveedores/templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    {% block css %}

    {% endblock css %}
    <title>
        {% block titulo %}

        {% endblock titulo %}
    </title>
</head>
<body>
  <div class="container">

    <nav  style="background-color:#605c34" style="color:#d3cbba" class="navbar navbar-expand-lg">
      <div style="background-color:#605c34" class="container-fluid">
        <a style="color:#d3cbba" class="navbar-brand" href="#">IEEZ</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a style="color:#d3cbba" class="nav-link active" aria-current="page" href="{% url 'productos:lista' %}">Productos</a>
            </li>
            <li class="nav-item dropdown">
              <a style="color:#d3cbba" class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Productos
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                <li><a style="color:#d3cbba" class="dropdown-item" href="{% url 'productos:lista' %}">Productos adquiridos</a></li>
                <li><a style="color:#d3cbba" class="dropdown-item" href="{% url 'tipoproducto:lista' %}">Tipo de Producto</a></li>
                
              </ul>
            </li>
            <li class="nav-item">
              <a style="color:#d3cbba" class="nav-link" href="{% url 'usuario:lista' %}">Usuarios</a>
            </li>
            <li class="nav-item">
              <a style="color:#d3cbba" class="nav-link" href="{% url 'proveedores:lista' %}">Proveedor</a>
            </li>
            
            <li class="nav-item">
              <a style="color:#d3cbba" class="nav-link" href="{% url 'departamentos:lista' %}">Departamentos</a>
            </li>
            <!--<li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown link
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>-->
            
          </ul>
        </div>
      </div>
    </nav>
    
    {% block contenido %}

    {% endblock contenido %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    {% block js %}

    {% endblock js %}

  </div> <!--cierra el div del container-->
  </body>
  </html>